// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "post": {
                "description": "資産マスター情報と個別資産情報を同時に作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset"
                ],
                "summary": "資産の新規作成",
                "parameters": [
                    {
                        "description": "資産作成リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateAssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/all": {
            "get": {
                "description": "登録されている全ての個別資産情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset"
                ],
                "summary": "全資産の一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/edit/{id}": {
            "put": {
                "description": "指定されたIDの個別資産情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset"
                ],
                "summary": "資産情報の更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "資産ID (Asset ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "資産更新リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EditAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/master/all": {
            "get": {
                "description": "登録されている全ての資産マスター情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset Master"
                ],
                "summary": "全資産マスターの一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetMasterListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/master/{id}": {
            "get": {
                "description": "指定されたIDの資産マスター情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset Master"
                ],
                "summary": "資産マスター情報の取得 (ID指定)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "資産マスターID (Asset Master ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetMasterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "指定されたIDの資産マスター情報を削除します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset Master"
                ],
                "summary": "資産マスター情報の削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "資産マスターID (Asset Master ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "description": "指定されたIDの個別資産情報を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset"
                ],
                "summary": "資産情報の取得 (ID指定)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "資産ID (Asset ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/disposal/all": {
            "get": {
                "description": "全ての資産廃棄履歴を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disposal"
                ],
                "summary": "全廃棄履歴の取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DisposalListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/disposal/{id}": {
            "get": {
                "description": "指定されたIDの廃棄履歴を取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disposal"
                ],
                "summary": "廃棄履歴の取得 (ID指定)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "廃棄ID (Disposal ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DisposalResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "指定された資産IDの資産を廃棄登録します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disposal"
                ],
                "summary": "資産の廃棄処理",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "資産ID (Asset ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "廃棄登録リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateDisposalRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lend/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "貸出情報一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LendListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lend/all/with-name": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "貸出情報一覧取得 (名称付き)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LendingDetailListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lend/edit/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "貸出情報編集",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貸出ID (Lend ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新情報",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EditLendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lend/return/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "備品返却処理",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貸出ID (Lend ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "返却情報",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ReturnAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lend/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "貸出情報取得 (ID指定)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貸出ID (Lend ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lend"
                ],
                "summary": "備品貸出処理",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "備品ID (Asset ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "貸出情報",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LendAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping応答を確認するためのハンドラー.そもそもswaggerが動いていればpongは絶対返ってくるはず。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping応答を確認",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.PingErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Asset": {
            "type": "object",
            "properties": {
                "default_location": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_master_id": {
                    "type": "integer"
                },
                "last_check_date": {
                    "type": "string"
                },
                "last_checker": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                }
            }
        },
        "domain.AssetMaster": {
            "type": "object",
            "properties": {
                "genre_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "management_category_id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.AssetsLend": {
            "type": "object",
            "properties": {
                "actual_return_date": {
                    "description": "実際の返却日 (\"YYYY-MM-DD\" or null)",
                    "type": "string"
                },
                "asset_id": {
                    "description": "貸出対象資産ID",
                    "type": "integer"
                },
                "borrower": {
                    "description": "借用者",
                    "type": "string"
                },
                "expected_return_date": {
                    "description": "返却予定日 (\"YYYY-MM-DD\" or null)",
                    "type": "string"
                },
                "id": {
                    "description": "主キー",
                    "type": "integer"
                },
                "lend_date": {
                    "description": "貸出日 (\"YYYY-MM-DD\")",
                    "type": "string"
                },
                "notes": {
                    "description": "備考 (null可)",
                    "type": "string"
                },
                "quantity": {
                    "description": "貸出数",
                    "type": "integer"
                }
            }
        },
        "domain.CreateAssetRequest": {
            "type": "object",
            "required": [
                "quantity",
                "status_id"
            ],
            "properties": {
                "asset_master_id": {
                    "description": "--- マスター情報（任意） ---",
                    "type": "integer"
                },
                "default_location": {
                    "type": "string"
                },
                "genre_id": {
                    "type": "integer"
                },
                "last_check_date": {
                    "type": "string"
                },
                "last_checker": {
                    "type": "string"
                },
                "management_category_id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "purchase_date": {
                    "description": "(形式: \"YYYY-MM-DD\")",
                    "type": "string"
                },
                "quantity": {
                    "description": "--- 個別資産情報 ---",
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateDisposalRequest": {
            "type": "object",
            "properties": {
                "is_individual": {
                    "description": "個別管理かどうか",
                    "type": "boolean"
                },
                "processed_by": {
                    "description": "処理者の学籍番号",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "domain.DisposalResponse": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "description": "対象資産 ID",
                    "type": "integer"
                },
                "disposal_date": {
                    "description": "廃棄日 (YYYY-MM-DD)",
                    "type": "string"
                },
                "id": {
                    "description": "主キー",
                    "type": "integer"
                },
                "processed_by": {
                    "description": "処理担当者",
                    "type": "string"
                },
                "quantity": {
                    "description": "廃棄数量",
                    "type": "integer"
                },
                "reason": {
                    "description": "廃棄理由",
                    "type": "string"
                }
            }
        },
        "domain.EditAssetRequest": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "description": "主キー",
                    "type": "integer"
                },
                "last_check_date": {
                    "type": "string"
                },
                "last_checker": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "quantity": {
                    "description": "更新時は任意",
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "status_id": {
                    "description": "更新時は任意, IDなのでint64",
                    "type": "integer"
                }
            }
        },
        "domain.EditLendRequest": {
            "type": "object",
            "required": [
                "borrower",
                "lend_date",
                "quantity"
            ],
            "properties": {
                "actual_return_date": {
                    "description": "NULL 可（通常登録時はNULL）",
                    "type": "string"
                },
                "borrower": {
                    "type": "string"
                },
                "expected_return_date": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "lend_date": {
                    "description": "\"YYYY-MM-DD\" 形式",
                    "type": "string"
                },
                "notes": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.LendAssetRequest": {
            "type": "object",
            "required": [
                "asset_id",
                "borrower",
                "lend_date",
                "quantity"
            ],
            "properties": {
                "actual_return_date": {
                    "description": "NULL 可（通常登録時はNULL）",
                    "type": "string"
                },
                "asset_id": {
                    "type": "integer"
                },
                "borrower": {
                    "type": "string"
                },
                "expected_return_date": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "lend_date": {
                    "description": "\"YYYY-MM-DD\" 形式",
                    "type": "string"
                },
                "notes": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.LendingDetail": {
            "type": "object",
            "properties": {
                "borrower": {
                    "type": "string"
                },
                "expected_return_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lend_date": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.ReturnAssetRequest": {
            "type": "object",
            "required": [
                "actual_return_date",
                "quantity"
            ],
            "properties": {
                "actual_return_date": {
                    "type": "string"
                },
                "lendID": {
                    "type": "integer"
                },
                "notes": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "quantity": {
                    "description": "返却数量",
                    "type": "integer"
                }
            }
        },
        "handler.AssetListResponse": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Asset"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Assets fetched successfully"
                }
            }
        },
        "handler.AssetMasterListResponse": {
            "type": "object",
            "properties": {
                "masters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AssetMaster"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Asset masters fetched successfully"
                }
            }
        },
        "handler.AssetMasterResponse": {
            "type": "object",
            "properties": {
                "master": {
                    "$ref": "#/definitions/domain.AssetMaster"
                },
                "message": {
                    "type": "string",
                    "example": "Asset master fetched successfully"
                }
            }
        },
        "handler.AssetResponse": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/domain.Asset"
                },
                "message": {
                    "type": "string",
                    "example": "Asset fetched successfully"
                }
            }
        },
        "handler.CreateAssetResponse": {
            "type": "object",
            "properties": {
                "asset_master_id": {
                    "type": "integer",
                    "example": 101
                },
                "message": {
                    "type": "string",
                    "example": "Asset created successfully"
                }
            }
        },
        "handler.DisposalListResponse": {
            "type": "object",
            "properties": {
                "disposals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DisposalResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Disposals fetched successfully"
                }
            }
        },
        "handler.DisposalResponseWrapper": {
            "type": "object",
            "properties": {
                "disposal": {
                    "$ref": "#/definitions/domain.DisposalResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Disposal fetched successfully"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "不正なリクエストです"
                }
            }
        },
        "handler.LendListResponse": {
            "type": "object",
            "properties": {
                "lends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AssetsLend"
                    }
                }
            }
        },
        "handler.LendResponse": {
            "type": "object",
            "properties": {
                "lend": {
                    "$ref": "#/definitions/domain.AssetsLend"
                },
                "message": {
                    "type": "string",
                    "example": "Fetch completed"
                }
            }
        },
        "handler.LendingDetailListResponse": {
            "type": "object",
            "properties": {
                "lends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LendingDetail"
                    }
                }
            }
        },
        "handler.PingErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal Server Error"
                }
            }
        },
        "handler.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "handler.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "処理に成功しました"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "備品管理システム",
	Description:      "研究室内の備品を管理するシステムです。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
