// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "post": {
                "description": "新しい備品情報を登録します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "新規備品を登録",
                "parameters": [
                    {
                        "description": "登録する備品情報",
                        "name": "asset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/master": {
            "get": {
                "description": "登録されているすべての備品マスタ情報を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "備品マスタ（すべて）を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/master/{id}": {
            "get": {
                "description": "指定されたIDを持つ単一の備品マスタ情報を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "備品マスタをIDで取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "備品マスタID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "description": "指定されたIDを持つ単一の備品情報を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "備品情報をIDで取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "備品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "指定されたIDの備品情報を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "備品情報を更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "備品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新する備品情報",
                        "name": "asset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EditAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/{id}/lend": {
            "post": {
                "description": "指定されたIDの備品を貸し出します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lends"
                ],
                "summary": "備品を貸出",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "備品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "貸出情報（貸出先ユーザーなど）",
                        "name": "lend",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LendAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assetsAll": {
            "get": {
                "description": "登録されているすべての備品情報を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "備品情報（すべて）を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AssetListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lends": {
            "get": {
                "description": "すべての貸出情報を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lends"
                ],
                "summary": "貸出情報（すべて）を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LendListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lends/{id}/return": {
            "post": {
                "description": "指定されたIDの貸出情報を「返却済み」にします。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lends"
                ],
                "summary": "備品を返却",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "貸出ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "返却情報（返却日など）",
                        "name": "return",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AssetReturnRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/nfc/read": {
            "get": {
                "description": "NFCリーダからカード情報を取得します。ダミーモード時はサンプル値を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nfc"
                ],
                "summary": "NFCカード情報の取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetNFCResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping応答を確認するためのハンドラーです。そもそもswaggerが動いていればpongは絶対返ってくるはず。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping応答を確認",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.PingErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Asset": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "item_master_id": {
                    "type": "integer"
                },
                "last_check_date": {
                    "type": "string"
                },
                "last_checker": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "serial_number": {
                    "description": "omitemptyは、値が空ならJSONに含めないというGoのタグ",
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                }
            }
        },
        "domain.AssetReturnRequest": {
            "type": "object",
            "required": [
                "lend_id",
                "quantity",
                "return_date"
            ],
            "properties": {
                "lend_id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "return_date": {
                    "type": "string"
                }
            }
        },
        "domain.AssetsLend": {
            "type": "object",
            "properties": {
                "actual_return_date": {
                    "description": "実際の返却日 (\"YYYY-MM-DD\" or null)",
                    "type": "string"
                },
                "asset_id": {
                    "description": "貸出対象資産ID",
                    "type": "integer"
                },
                "borrower": {
                    "description": "借用者",
                    "type": "string"
                },
                "expected_return_date": {
                    "description": "返却予定日 (\"YYYY-MM-DD\" or null)",
                    "type": "string"
                },
                "id": {
                    "description": "主キー",
                    "type": "integer"
                },
                "lend_date": {
                    "description": "貸出日 (\"YYYY-MM-DD\")",
                    "type": "string"
                },
                "notes": {
                    "description": "備考 (null可)",
                    "type": "string"
                },
                "quantity": {
                    "description": "貸出数",
                    "type": "integer"
                }
            }
        },
        "domain.CreateAssetRequest": {
            "type": "object",
            "required": [
                "asset",
                "asset_master"
            ],
            "properties": {
                "asset": {
                    "description": "assets テーブル相当（個別資産）",
                    "type": "object",
                    "required": [
                        "quantity",
                        "status_id"
                    ],
                    "properties": {
                        "item_master_id": {
                            "description": "マスタ登録後に判明するのでフロントからはNULL許容",
                            "type": "integer"
                        },
                        "last_check_date": {
                            "description": "\"2024-01-01\"",
                            "type": "string"
                        },
                        "last_checker": {
                            "type": "string"
                        },
                        "location": {
                            "type": "string"
                        },
                        "notes": {
                            "type": "string"
                        },
                        "owner": {
                            "type": "string"
                        },
                        "purchase_date": {
                            "description": "\"2024-01-01\" 形式",
                            "type": "string"
                        },
                        "quantity": {
                            "type": "integer"
                        },
                        "serial_number": {
                            "type": "string"
                        },
                        "status_id": {
                            "type": "integer"
                        }
                    }
                },
                "asset_master": {
                    "description": "assets_masters テーブル相当（同時登録の場合）",
                    "type": "object",
                    "required": [
                        "management_category_id",
                        "name"
                    ],
                    "properties": {
                        "genre_id": {
                            "description": "NULL許容",
                            "type": "integer"
                        },
                        "management_category_id": {
                            "type": "integer"
                        },
                        "manufacturer": {
                            "description": "NULL許容",
                            "type": "string"
                        },
                        "model_number": {
                            "description": "NULL許容",
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "domain.EditAssetRequest": {
            "type": "object",
            "required": [
                "quantity",
                "status_id"
            ],
            "properties": {
                "asset_id": {
                    "description": "主キー",
                    "type": "integer"
                },
                "last_check_date": {
                    "description": "\"2024-01-01\"",
                    "type": "string"
                },
                "last_checker": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "purchase_date": {
                    "description": "\"2024-01-01\" 形式",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                }
            }
        },
        "domain.LendAssetRequest": {
            "type": "object",
            "required": [
                "asset_id",
                "borrower",
                "lend_date",
                "quantity"
            ],
            "properties": {
                "actual_return_date": {
                    "description": "NULL 可（通常登録時はNULL）",
                    "type": "string"
                },
                "asset_id": {
                    "type": "integer"
                },
                "borrower": {
                    "type": "string"
                },
                "expected_return_date": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "lend_date": {
                    "description": "\"YYYY-MM-DD\" 形式",
                    "type": "string"
                },
                "notes": {
                    "description": "NULL 可",
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.StudentCardInfo": {
            "type": "object",
            "properties": {
                "student_number": {
                    "type": "string"
                }
            }
        },
        "handler.AssetListResponse": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Asset"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Assets list retrieved successfully"
                }
            }
        },
        "handler.AssetResponse": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/domain.Asset"
                },
                "message": {
                    "type": "string",
                    "example": "Equipment retrieved successfully"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "エラーメッセージ"
                }
            }
        },
        "handler.GetNFCResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.StudentCardInfo"
                },
                "message": {
                    "type": "string",
                    "example": "NFC data retrieved successfully"
                }
            }
        },
        "handler.IDResponse": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "type": "integer",
                    "example": 123
                },
                "message": {
                    "type": "string",
                    "example": "Asset created successfully"
                }
            }
        },
        "handler.LendListResponse": {
            "type": "object",
            "properties": {
                "lends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AssetsLend"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Lends retrieved successfully"
                }
            }
        },
        "handler.PingErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal Server Error"
                }
            }
        },
        "handler.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "handler.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "処理が正常に完了しました"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "備品管理システム",
	Description:      "研究室内の備品を管理するシステムです。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
